name: Question about GoLogger
description: Have a question about GoLogger or have any issues getting it to work properly? 

body:
  - type: markdown
    attributes:
      value: |
        Any questions about the basic functionality and features of GoLogger? Ask them here and I will do my best to answer you promptly.

  - type: textarea
    attributes:
      label: Your GoLogger question
      description: |
        Describe your question and provide screenshots if applicable.
    validations:
      required: true
